openapi: 3.1.0
info:
  title: OpenSearch Search Relevance API
  description: OpenSearch Search Relevance API.
  version: 1.0.0
paths:
  _plugins/search_relevance/query_sets:
    get:
      operationId: search_relevance.get_query_sets.0
      x-operation-group: search_relevance.get_query_sets
      x-version-added: '3.1'
      description: Lists the current query sets available.
      responses:
        '200':
          $ref: '#/components/responses/query_sets_list@200'
    post:
      operationId: search_relevance.post_query_sets.0
      x-operation-group: search_relevance.post_query_sets
      x-version-added: '3.1'
      description: Creates a new query set by sampling queries from the user behavior data. 
      requestBody:
        $ref: '#/components/requestBodies/create_query'
      responses:
        '200':
          $ref: '#/components/responses/query_set_creation@200'
    put:
      operationId: search_relevance.put_query_sets.0
      x-operation-group: search_relevance.put_query_sets
      x-version-added: '3.1'
      description: Creates a new query set by uploading manually.
      requestBody:
        $ref: '#/components/requestBodies/put_query'
      responses:
        '200':
          $ref: '#/components/responses/query_set_creation@200'
  _plugins/search_relevance/query_sets/{query_set_id}:
    get:
      operationId: search_relevance.get_query_sets.1
      x-operation-group: search_relevance.get_query_sets
      x-version-added: '3.1'
      description: Gets a specified query set.
      parameters:
        - $ref: '#/components/parameters/query_set_id'
      responses:
        '200':
          $ref: '#/components/responses/query_set@200'
    delete:
      operationId: search_relevance.delete_query_sets.0
      x-operation-group: search_relevance.delete_query_sets
      x-version-added: '3.1'
      description: Deletes a query set.
      parameters:
        - $ref: '#/components/parameters/query_set_id'
      responses:
        '200':
          $ref: '#/components/responses/query_set_deletion@200'
  _plugins/search_relevance/judgments:
    get:
      operationId: search_relevance.get_judgments.0
      x-operation-group: search_relevance.get_judgments
      x-version-added: '3.1'
      description: Gets the list of judgments.
      responses:
        '200':
          $ref: '#/components/responses/judgment_list@200'
    put:
      operationId: search_relevance.put_judgments.0
      x-operation-group: search_relevance.put_judgments
      x-version-added: '3.1'
      description: Creates a judgment.
      requestBody:
        description: The request body of the judgment to be created.
        #This part is not working at the moment because the oneOf is not being processed properly. 
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/put_judgment_ubi'
                - $ref: '#/components/schemas/put_judgment_llm'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: 
                  object
                properties:
                  judgment_id:
                    type: string
  _plugins/search_relevance/judgments/{judgment_id}:
    get:
      operationId: search_relevance.get_judgments.1
      x-operation-group: search_relevance.get_judgments
      x-version-added: '3.1'
      description: Gets a specified judgment.
      parameters:
        - $ref: '#/components/parameters/judgment_id'
      responses:
        '200':
          $ref: '#/components/responses/judgment@200'
    delete:
      operationId: search_relevance.delete_judgments.0
      x-operation-group: search_relevance.delete_judgments
      x-version-added: '3.1'
      description: Deletes a specified judgment.
      parameters:
        - $ref: '#/components/parameters/judgment_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: string
                  result:
                    type: string
  _plugins/search_relevance/search_configurations:
    get:
      operationId: search_relevance.get_search_configurations.0
      x-operation-group: search_relevance.get_search_configurations
      x-version-added: '3.1'
      description: Gets the list of search configurations.
      responses:
        '200':
          $ref: '#/components/responses/search_configurations_list@200'
    put:
      operationId: search_relevance.put_search_configurations.0
      x-operation-group: search_relevance.put_search_configurations
      x-version-added: '3.1'
      description: Creates a search configuration.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                query:
                  type: string
                index:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  search_configuration_id:
                    type: string
                  search_configuration_result:
                    type: string
  _plugins/search_relevance/search_configurations/{search_configuration_id}:
    get:
      operationId: search_relevance.get_search_configurations.1
      x-operation-group: search_relevance.get_search_configurations
      x-version-added: '3.1'
      description: Gets a specified search configuration.
      parameters:
        - $ref: '#/components/parameters/search_configuration_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../schemas/search_relevance._common.yaml#/components/schemas/SearchConfiguration'
    delete:
      operationId: search_relevance.delete_search_configurations.0
      x-operation-group: search_relevance.delete_search_configurations
      x-version-added: '3.1'
      description: Deletes a specified search configuration.
      parameters:
        - $ref: '#/components/parameters/search_configuration_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                #properties:
                #  id: 
                #    type: string
                #  result:
                #    type: string
  _plugins/search_relevance/experiments:
    get:
      operationId: search_relevance.get_experiments.0
      x-operation-group: search_relevance.get_experiments
      x-version-added: '3.1'
      description: Gets the list of experiments.
      responses:
        '200':
          $ref: '#/components/responses/experiments_list@200'
    put:
      operationId: search_relevance.put_experiments.0
      x-operation-group: search_relevance.put_experiments
      x-version-added: '3.1'
      description: Creates an experiment.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                querySetId:
                  type: string
                searchConfigurationList:
                  type: array
                  items:
                    type: string
                size:
                  type: integer
                type:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                #properties:
                #  experiments_id:
                #    type: string
                #  experiments_result:
                #    type: string
  _plugins/search_relevance/experiments/{experiment_id}:
    get:
      operationId: search_relevance.get_experiments.1
      x-operation-group: search_relevance.get_experiments
      x-version-added: '3.1'
      description: Gets a specified experiment.
      parameters:
        - $ref: '#/components/parameters/experiment_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                #$ref: '../schemas/search_relevance._common.yaml#/components/schemas/Experiment'
    delete:
      operationId: search_relevance.delete_experiments.0
      x-operation-group: search_relevance.delete_experiments
      x-version-added: '3.1'
      description: Deletes a specified experiment.
      parameters:
        - $ref: '#/components/parameters/experiment_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                #properties:
                #  id: 
                #    type: string
                #  result:
                #    type: string
components:
  parameters:
    query_set_id: 
      name: query_set_id
      in: path
      description: The query set id
      schema:
        type: string
    judgment_id:
      name: judgment_id
      in: path
      description: The judgment id
      schema:
        type:
          string
    search_configuration_id:
      name: search_configuration_id
      in: path
      description: The search configuration id
      schema:
        type:
          string
    experiment_id:
      name: experiment_id
      in: path
      description: The experiment id
      schema:
        type:
          string
  schemas:
    put_judgment_ubi:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        querySetId:
          type: string
        clickModel:
          type: string
        maxRank:
          type: integer
    put_judgment_llm:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        querySetId:
          type: string
        modelId:
          type: string
        maxRank:
          type: integer
        searchConfigurationList:
          type: array
          items:
            type: string
  requestBodies:
    create_query:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              sampling:
                type: string
              querySetSize:
                type: integer
    put_query:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              sampling:
                type: string
              querySetQueries:
                type: array
                items:
                  type: object
    put_judgment_ubi:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        querySetId:
          type: string
        clickModel:
          type: string
        maxRank:
          type: integer
    put_judgment_llm:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        querySetId:
          type: string
        modelId:
          type: string
        maxRank:
          type: integer
        searchConfigurationList:
          type: array
          items:
            type: string
  responses:
    query_set@200:
      content:
        application/json:
          schema:
            type: object
            #$ref: '../schemas/search_relevance._common.yaml#/components/schemas/QuerySet'
    query_sets_list@200:
      content:
        application/json:
          schema:
            type: object
            #items: 
            #  $ref: '../schemas/search_relevance._common.yaml#/components/schemas/QuerySet'
    query_set_creation@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              query_set_id: 
                type: string
              query_set_result:
                type: string
    query_set_deletion@200:
      content:
        application/json:
          schema:
            type: object
            #properties:
            #  id: 
            #    type: string
            #  result:
            #    type: string
    judgment_list@200:
      content:
        application/json:
          schema:
            type: object
            #items:
            #  $ref: '../schemas/search_relevance._common.yaml#/components/schemas/Judgment'
    search_configurations_list@200:
      content:
        application/json:
          schema:
          type: object
            #type: array
            #items:
            #  $ref: '../schemas/search_relevance._common.yaml#/components/schemas/SearchConfiguration'
    judgment@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/search_relevance._common.yaml#/components/schemas/Judgment'
    experiments_list@200:
      content:
        application/json:
          schema:
            type: object
            #type: array
            #items:
            #  $ref: '../schemas/search_relevance._common.yaml#/components/schemas/Experiment'
