openapi: 3.1.0
info:
  title: OpenSearch Search Relevance API
  description: OpenSearch Search Relevance API.
  version: 1.0.0
paths:
  _plugins/search_relevance/query_sets:
    get:
      operationId: search_relevance.get_query_sets.0
      x-operation-group: search_relevance.get_query_sets
      x-version-added: '3.0'
      description: Lists the current query sets available.
      responses:
        '200':
          $ref: '#/components/responses/query_sets_list@200'
    post:
      operationId: search_relevance.post_query_sets.1
      x-operation-group: search_relevance.post_query_sets
      x-version-added: '3.0'
      description: Creates a new query set by sampling queries from the user behavior data. 
      requestBody:
        $ref: '#/components/requestBodies/create_query'
      responses:
        '200':
          $ref: '#/components/responses/query_set_creation@200'
    put:
      operationId: search_relevance.put_query_sets.2
      x-operation-group: search_relevance.put_query_sets
      x-version-added: '3.0'
      description: Creates a new query set by uploading manually.
      requestBody:
        $ref: '#/components/requestBodies/put_query'
      responses:
        '200':
          $ref: '#/components/responses/query_set_creation@200'
  _plugins/search_relevance/query_sets/{query_set_id}:
    delete:
      operationId: search_relevance.delete_query_sets.3
      x-operation-group: search_relevance.delete_query_sets
      x-version-added: '3.0'
      description: Deletes a query set.
      parameters:
        - $ref: '#/components/parameters/query_set_id'
      responses:
        '200':
          $ref: '#/components/responses/query_set_deletion@200'

components:
  parameters:
    query_set_id: 
      name: query_set_id
      in: path
      description: The query set id
      schema:
        type: string
  requestBodies:
    create_query:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              sampling:
                type: string
              querySetSize:
                type: integer
    put_query:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              sampling:
                type: string
              querySetQueries:
                type: string
  responses:
    query_sets_list@200:
      content:
        application/json:
          schema:
            type: array
            items: 
              $ref: '../schemas/search_relevance._common.yaml#/components/schemas/QuerySet'
    query_set_creation@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              query_set_id: 
                type: string
              query_set_result:
                type: string
    query_set_deletion@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              id: 
                type: string
              result:
                type: string
