openapi: 3.1.0
info:
  title: Schemas of Search Relevance
  description: Schemas of Search Relevance.
  version: 1.0.0
paths: {}
components:
  schemas:
    QuerySet:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        sampling:
          type: string
        timestamp:
          type: string
        querySetQueries:
          type: object
        
