openapi: 3.1.0
info:
  title: Schemas of Search Relevance
  description: Schemas of Search Relevance.
  version: 1.0.0
paths: {}
components:
  schemas:
    QuerySet:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        sampling:
          type: string
        timestamp:
          type: string
        querySetQueries:
          type: object # I am also not completely sure how to test that the output
          # of the querySetQueries is correct because it is objcet which is dependent
          # on the input to the query set creation prior. 
    Judgment:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
        name:
          type: string
        status:
          type: string
        type:
          type: string
        metadata:
          type: object
        judgmentScores:
          type: object
    SearchConfiguration:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        timestamp:
          type: string
        index:
          type: string
        query:
          type: string
        searchPipeline:
          type: string
    Experiment:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
        type:
          type: string
        status:
          type: string
        querySetId:
          type: string
        searchConfigurationList:
          type: array
          items:
            type: string
        judgmentList:
          type: array
          items:
            type: string
        size:
          type: integer
        results:
          type: object
    GenericObject:
      type: object
      properties:
        took:
          type: integer
        timed_out: 
          type: boolean
        _shards:
          type: object
        hits:
          type: object
